name: Publish release

on: workflow_dispatch

permissions:
  contents: write

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ghidra: [ "10.2.3", "10.3.3", "10.4" ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
      - uses: er28-0652/setup-ghidra@master
        with:
          version: ${{ matrix.ghidra }}
      - uses: eskatos/gradle-command-action@v2
        with:
          gradle-version: 7.3
          arguments: buildExtension -PGHIDRA_INSTALL_DIR=${{ env.GHIDRA_INSTALL_DIR }}
      - uses: actions/upload-artifact@v3
        with:
          name: Ghidra-Cpp-Class-Analyzer_${{ matrix.ghidra }}
          path: dist/*.zip
      - uses: ncipollo/release-action@v1
        with:
          if: false
          artifacts: "dist/*.zip"
          tag: ${{ matrix.ghidra }}
          allowUpdates: true
          artifactErrorsFailBuild: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
