name: Run tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghidra: ["10.2"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
      - uses: er28-0652/setup-ghidra@master
        with:
          version: ${{ matrix.ghidra }}
      - uses: eskatos/gradle-command-action@v2
        with:
          gradle-version: 7.3
          arguments: test --info -PGHIDRA_INSTALL_DIR=${{ env.GHIDRA_INSTALL_DIR }}
